### ISSUE TITLE
compose2nomad.rb:28:in `absolute_path': no implicit conversion of nil into String (TypeError)

### ISSUE THREAD

**Issue by a-t-u-l-k** [jovandeginste/nomad-compose#1]
[docker-compose.yml.txt](https://github.com/jovandeginste/nomad-compose/files/1368081/docker-compose.yml.txt)

**Comment by jxub** [comment]
Still having a problem with this:
```
./nomad-compose/compose2nomad.rb langid-docker-compose/docker-compose.yml
./nomad-compose/compose2nomad.rb:28:in `absolute_path': no implicit conversion of nil into String (TypeError)
	from ./nomad-compose/compose2nomad.rb:28:in `load_compose'
	from ./nomad-compose/compose2nomad.rb:40:in `<main>'
```

**Comment by cocowalla** [comment]
Same here, it happens with every docker compose YAML file I use, even if I simplify it down to nothing

**Comment by julianpistorius** [comment]
The only way I've managed to get it to work is to remove the top-level `services:` element and have the services all as siblings in the top level of the file. 🤷‍♂

**Comment by jameski83** [comment]
has anyone got this to work or found any similar tools to convert docker compose files for use with nomad?
